EMS_Front_End/EMS_Web_App/Controllers/ElectionController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using EMS_Web_App.StaticFunc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace EMS_Web_App.Controllers
{
    public class ElectionController : Controller
    {
        private readonly ITransactionHandler _api;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ElectionController(ILogger<HomeController> logger, 
                                            IOptions<APISettings> apiSettings,
                                            ITransactionHandler api,
                                            IHttpContextAccessor httpContextAccessor)
        {
            _apiSettings = apiSettings.Value;
            _api = api;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }
        public async Task<IActionResult> Index()
        {
            List<election_year_to_date> data =  await _api.GetElectionList(_token, _apiSettings.BaseURL, Constant.GetElection);
            return View(data);
        }
        public IActionResult Add()
        {
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            APIResponse response = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.GetElectionById, id.ToString());
            election_year_to_date result = GenericFunc.ExtractJsonData<election_year_to_date>(response.Data!.ToString());            
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_year_to_date model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.AddElection, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }                              
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_year_to_date model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.UpdateElection, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }
            }
            catch
            {
                return View();
            }

        }
    }
}

EMS_Front_End/EMS_Web_App/Views/Election/Add.cshtml
@model election_year_to_date
@{
    ViewData["Title"] = "Add Election";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Election" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Add" asp-controller="Election" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.election_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_start_date_time, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_start_date_time, Constant.DateTimeFormat, htmlAttributes: new { @class = "form-control input_text", type = "datetime-local", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_start_date_time, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_end_date_time, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_end_date_time, Constant.DateTimeFormat, htmlAttributes: new { @class = "form-control input_text", type = "datetime-local", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_end_date_time, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>

EMS_Front_End/EMS_Web_App/Views/Election/Edit.cshtml
@model election_year_to_date
@{
    ViewData["Title"] = "Edit Election";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Election" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Edit" asp-controller="Election" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <input type="hidden" asp-for="election_id" />
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.election_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_start_date_time, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_start_date_time, Constant.DateTimeFormat, htmlAttributes: new { @class = "form-control input_text datetimepicker", type = "datetime-local", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_start_date_time, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_end_date_time, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_end_date_time, Constant.DateTimeFormat, htmlAttributes: new { @class = "form-control input_text datetimepicker", type = "datetime-local", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_end_date_time, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_current_status, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        <label>@Html.RadioButtonFor(model => model.election_current_status, 1) Active</label>
                        <label>@Html.RadioButtonFor(model => model.election_current_status, 4) Cancel</label>
                    </div>
                    @Html.ValidationMessageFor(model => model.election_current_status, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <br />
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

EMS_Front_End/EMS_Web_App/Views/Election/Index.cshtml
@model List<election_year_to_date>
@{
    ViewData["Title"] = "List of Election";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Election" asp-action="Add"><input type="button" class="view" value="Create" /></a>
    </div>
    <div class="report-body">
        <div class="report-topic-heading">
            <h3 class="t-op">+</h3>
            <h3 class="t-op">Election Name</h3>
            <h3 class="t-op">Election Start Date</h3>
            <h3 class="t-op">Election End Date</h3>
            <h3 class="t-op">Election IsActive</h3>
        </div>
        <div class="items">
            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    <div class="item1">
                        <h3 class="t-op-nextlvl">
                            @if (item.election_current_status == 1)
                            {
                                <a asp-controller="Election" asp-action="Edit" asp-route-id="@item.election_id"><i class="fa-solid fa-pen-to-square"></i></a>
                            }
                            else
                            {
                                <a><i class="fa-solid fa-square"></i></a>
                                
                            }
                        </h3>
                        <h3 class="t-op-nextlvl">@item.election_name</h3>
                        <h3 class="t-op-nextlvl">@item.election_start_date_time</h3>
                        <h3 class="t-op-nextlvl">@item.election_end_date_time</h3>
                        <h3 class="t-op-nextlvl label-tag">@(item.election_current_status == 1 ? "Active" : (item.election_current_status == 2 ? "In Progress" : (item.election_current_status == 3 ? "Completed" : "Cancelled")))</h3>
                    </div>
                }
            }
        </div>
    </div>
</div>