EMS_Front_End/EMS_Web_App/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;

namespace EMS_Web_App.Controllers
{
    [Authorize("Permission")]
    public class CityController : Controller
    {
        private readonly IAPIHandler<election_city> _api;
        private readonly ITransactionHandler _apiDD;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CityController(ILogger<HomeController> logger, IAPIHandler<election_city> api,
                                            IOptions<APISettings> apiSettings,
                                            ITransactionHandler apiDD,
                                            IHttpContextAccessor httpContextAccessor)
        {
            _api = api;
            _apiSettings = apiSettings.Value;
            _apiDD = apiDD;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }

        public async Task<IActionResult> Index()
        {
            List<election_city> states = await _api.GetAllData(_token, _apiSettings.BaseURL, Constant.CityGetAll);

            return View(states);
        }

        public async Task<IActionResult> Edit(int id)
        {
            await LoadState();
            election_city states = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.CityGetById, id);

            return View(states);
        }
        public async Task<IActionResult> Add()
        {
            await LoadState();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_city model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.CityADD, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");
                }
                else
                    ModelState.AddModelError("", "Invalid data.");

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_city model)
        {
            try
            {
                string result = "";

                if (ModelState.IsValid)
                {
                    result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.CityUPDATE, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");
                }
                else
                    ModelState.AddModelError("", "Invalid data.");


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private async Task<bool> LoadState()
        {
            var states = await _apiDD.GetActiveList(_apiSettings.BaseURL, Constant.GetDDState);

            if (states != null)
            {
                ViewBag.StateDrpList = new SelectList(states, "election_state_id", "election_state_name");
                return true;
            }
            else
                return false;
        }
    }
}

EMS_Front_End/EMS_Web_App/Controllers/MPSeatController.cs
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using EMS_Web_App.StaticFunc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

namespace EMS_Web_App.Controllers
{
    [Authorize("Permission")]
    public class MPSeatController : Controller
    {
        private readonly ITransactionHandler _api;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MPSeatController(ILogger<HomeController> logger,
                                            IOptions<APISettings> apiSettings,
                                            ITransactionHandler api,
                                            IHttpContextAccessor httpContextAccessor)
        {
            _apiSettings = apiSettings.Value;
            _api = api;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }
        public async Task<IActionResult> Index()
        {
            APIResponse response = await _api.GetDataList(_token, _apiSettings.BaseURL, Constant.GetMPSeat);
            List<election_mp_seat_lists> result = GenericFunc.ExtractJsonData<List<election_mp_seat_lists>>(response.Data!.ToString());
            return View(result);
        }
        public async Task<IActionResult> Add()
        {
            await LoadData();
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            await LoadData();
            APIResponse response = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.GetMPSeatyId, id.ToString());
            election_mp_seat_by_state result = GenericFunc.ExtractJsonData<election_mp_seat_by_state>(response.Data!.ToString());
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_mp_seat_by_state model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.AddMPSeat, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        await LoadData();
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    await LoadData();
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_mp_seat_by_state model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.UpdateMPSeat, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        await LoadData();
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    await LoadData();
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
        private async Task<bool> LoadData()
        {
            var states = await _api.GetActiveList(_apiSettings.BaseURL, Constant.GetDDState);
            APIResponse elections = await _api.GetDataList(_token, _apiSettings.BaseURL, Constant.GetActiveElectionList);
            List<election_year_to_date> result = GenericFunc.ExtractJsonData<List<election_year_to_date>>(elections.Data!.ToString());

            if (states != null || result != null)
            {
                if(states != null)
                    ViewBag.StateDrpList = new SelectList(states, "election_state_id", "election_state_name");

                if (result != null)
                    ViewBag.ElectionDrpList = new SelectList(result, "election_id", "election_name");

                return true;
            }
            else
                return false;
        }
    }
}

EMS_Front_End/EMS_Web_App/Controllers/PartyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EMS_Web_App.Controllers
{
    public class PartyController : Controller
    {
        private readonly IAPIHandler<election_parties> _api;
        private readonly ITransactionHandler _apiDD;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PartyController(ILogger<HomeController> logger, IAPIHandler<election_parties> api,
                                            IOptions<APISettings> apiSettings,
                                            ITransactionHandler apiDD,
                                            IHttpContextAccessor httpContextAccessor)
        {
            _api = api;
            _apiSettings = apiSettings.Value;
            _apiDD = apiDD;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }

        public async Task<IActionResult> Index()
        {
            List<election_parties> parties = await _api.GetAllData(_token, _apiSettings.BaseURL, Constant.PartyGetAll);

            return View(parties);
        }

        public async Task<IActionResult> Edit(int id)
        {
            await LoadState();
            election_parties states = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.PartyGetById, id);

            return View(states);
        }
        public async Task<IActionResult> Add()
        {
            await LoadState();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_parties model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.PartyADD, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");
                }
                else
                    ModelState.AddModelError("", "Invalid data.");

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_parties model)
        {
            try
            {
                string result = "";

                if (ModelState.IsValid)
                {
                    result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.PartyUPDATE, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");
                }
                else
                    ModelState.AddModelError("", "Invalid data.");


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private async Task<bool> LoadState()
        {
            var data = await _apiDD.GetActiveList(_token, _apiSettings.BaseURL, Constant.GetDDSymbol);

            if (data != null)
            {
                ViewBag.SymDrpList = new SelectList(data, "election_sym_id", "election_sym_name");
                return true;
            }
            else
                return false;
        }
    }
}

EMS_Front_End/EMS_Web_App/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace EMS_Web_App.Controllers
{
    [Authorize("Permission")]
    public class StateController : Controller
    {
        private readonly IAPIHandler<election_state> _api;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public StateController(IAPIHandler<election_state> api, IOptions<APISettings> apiSettings,
                                                            IHttpContextAccessor httpContextAccessor)
        {
            _api = api;
            _apiSettings = apiSettings.Value;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }

        public async Task<IActionResult> Index()
        {
            List<election_state> states = await _api.GetAllData(_token, _apiSettings.BaseURL, Constant.StateGetAll);

            return View(states);
        }

        public async Task<IActionResult> Edit(int id)
        {
            election_state states = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.StateGetById, id);

            return View(states);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_state model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.StateADD, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View();
                }                                 
            }
            catch
            {
                return View();
            }
              
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_state model)
        {
            try
            {
                string result = "";

                if (ModelState.IsValid)
                {
                    result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.StateUPDATE, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

EMS_Front_End/EMS_Web_App/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor _httpContextAccessor
@{
    var UserType = StaticValue.UserType(_httpContextAccessor, Constant.RoleClaimType);
    var UserName = StaticValue.UserType(_httpContextAccessor, Constant.SurNameClaimType);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Constant.TITLE</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <!-- for header part -->
    <header>
        <div class="logosec">
            <div class="logo">
                <img src="~/img/ToVote.jpg"
                     class="icn"
                     style="margin-top: 11px;width: 100px;"
                     alt="" title="Right To Vote">
            </div>
            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210182541/Untitled-design-(30).png"
                 class="icn menuicn"
                 id="menuicn"
                 alt="menu-icon">
        </div>
        @*<div class="searchbar">
            <input type="text" placeholder="Search">
            <div class="searchbtn">
                <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210180758/Untitled-design-(28).png"
                     class="icn srchicn"
                     alt="search-icon">
            </div>
        </div>*@
    <div class="message">
        @UserName
        @*<div class="circle"></div>*@
        <a asp-area="" asp-controller="Account" asp-action="LogOut">
            <img src="~/img/logout-8.png"
                 class="icn"
                 alt="" title="Log out">
        </a>
        @*<div class="dp">
            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210180014/profile-removebg-preview.png"
            class="dpicn"
            alt="dp">
        </div>*@
    </div>
    </header>
    <div class="main-container">
        <div class="navcontainer">
            <nav class="nav">
                <div class="nav-upper-options">
                    @if (UserType == Constant.AType)
                    {
                        <div class="option2 nav-option">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210182148/Untitled-design-(29).png"
                                 class="nav-img"
                                 alt="dashboard">
                            <h3><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></h3>
                        </div>
                        <div class="option2 nav-option">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183322/9.png"
                                 class="nav-img"
                                 alt="articles">
                            <h3> <a asp-area="" asp-controller="Election" asp-action="Index">Announcement</a></h3>
                        </div>
                        <div class="option2 nav-option">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183322/9.png"
                                 class="nav-img"
                                 alt="articles">
                            <h3> <a asp-area="" asp-controller="MPSeat" asp-action="Index">Seat Allotment</a></h3>
                        </div>
                        <div class="option2 nav-option">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183322/9.png"
                                 class="nav-img"
                                 alt="articles">
                            <h3> <a asp-area="" asp-controller="Canditure" asp-action="Index">Enroll Candidate</a></h3>
                        </div>
                        <div class="nav-option nav-option6">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183320/4.png"
                                 class="nav-img"
                                 alt="articles">
                            <h3> <a asp-area="" asp-controller="Party" asp-action="Index">Party</a></h3>
                        </div>
                        <div class="nav-option option3">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183320/5.png"
                                 class="nav-img"
                                 alt="report">
                            <h3> <a asp-area="" asp-controller="State" asp-action="Index">State</a></h3>
                        </div>

                        <div class="nav-option option4">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183321/6.png"
                                 class="nav-img"
                                 alt="institution">
                            <h3> <a asp-area="" asp-controller="City" asp-action="Index">City</a></h3>
                        </div>

                        <div class="nav-option option5">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183323/10.png"
                                 class="nav-img"
                                 alt="blog">
                            <h3> <a asp-area="" asp-controller="Symbol" asp-action="Index">Symbol</a></h3>
                        </div>
                        <div class="nav-option logout">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210183321/7.png"
                                 class="nav-img"
                                 alt="logout">
                            <h3><a asp-area="" asp-controller="Account" asp-action="LogOut">Logout</a></h3>
                        </div>
                    }
                    else if(UserType == Constant.UType)
                    {
                        <div class="option2 nav-option">
                            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210182148/Untitled-design-(29).png"
                                 class="nav-img"
                                 alt="dashboard">
                            <h3><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></h3>
                        </div>
                    }
                </div>
            </nav>
        </div>
        <div class="main">
            <div class="searchbar2">
                <input type="text"
                       name=""
                       id=""
                       placeholder="Search">
                <div class="searchbtn">
                    <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210180758/Untitled-design-(28).png"
                         class="icn srchicn"
                         alt="search-button">
                </div>
            </div>
            @if (TempData["alertMsg"] != null)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.Raw(TempData["alertMsg"])
                        </div>
                    </div>
                </div>
                <script type="text/javascript">function ClosePP() {
                        $("#alertPP").hide();
                    }</script>
            }
            @RenderBody()            
        </div>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year.ToString() - @Constant.TITLE
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>