EMS_Front_End/EMS_Web_App/Controllers/SymbolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace EMS_Web_App.Controllers
{
    [Authorize("Permission")]
    public class SymbolController : Controller
    {
        private readonly IAPIHandler<election_symbols> _api;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public SymbolController(IAPIHandler<election_symbols> api, IOptions<APISettings> apiSettings,
                                                                IHttpContextAccessor httpContextAccessor)
        {
            _api = api;
            _apiSettings = apiSettings.Value;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }

        public async Task<IActionResult> Index()
        {
            List<election_symbols> symbols = await _api.GetAllData(_token, _apiSettings.BaseURL, Constant.SymbolGetAll);

            return View(symbols);
        }

        public async Task<IActionResult> Edit(int id)
        {
            election_symbols symbols = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.SymbolGetById, id);

            return View(symbols);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_symbols model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.SymbolADD, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View();
                }
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_symbols model)
        {
            try
            {
                string result = "";

                if (ModelState.IsValid)
                {
                    result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.SymbolUPDATE, model);

                    if (result != "")
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result);
                    else
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, "Unknown error");

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid data.");
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

EMS_Front_End/EMS_Web_App/Views/Symbol/Add.cshtml
@model election_symbols
@{
    ViewData["Title"] = "Add Symbol";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Symbol" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Add" asp-controller="Symbol" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_sym_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_sym_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_sym_name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_sym_font_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_sym_font_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_sym_font_name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>

EMS_Front_End/EMS_Web_App/Views/Symbol/Edit.cshtml
@model election_symbols
@{
    ViewData["Title"] = "Edit Symbol";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Symbol" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Edit" asp-controller="Symbol" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <input type="hidden" asp-for="election_sym_id" />
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_sym_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_sym_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_sym_name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_sym_font_name, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.election_sym_font_name, htmlAttributes: new { @class = "form-control input_text", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.election_sym_font_name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_sym_active, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.RadioButtonFor(model => model.election_sym_active, true) Active
                        @Html.RadioButtonFor(model => model.election_sym_active, false) In Active
                    </div>
                    @Html.ValidationMessageFor(model => model.election_sym_active, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <br />
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

EMS_Front_End/EMS_Web_App/Views/Symbol/Index.cshtml
@model List<election_symbols>
@{
    ViewData["Title"] = "List of Symbol";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Symbol" asp-action="Add"><input type="button" class="view" value="Create" /></a>
    </div>
    <div class="report-body">
        <div class="report-topic-heading">
            <h3 class="t-op">+</h3>
            <h3 class="t-op">Symbol Name</h3>
            <h3 class="t-op">Symbol</h3>
            <h3 class="t-op">Symbol IsActive</h3>
        </div>
        <div class="items">
            @foreach (var item in Model)
            {
                <div class="item1">
                    <h3 class="t-op-nextlvl"><a asp-controller="Symbol" asp-action="Edit" asp-route-id="@item.election_sym_id"><i class="fa-solid fa-pen-to-square"></i></a></h3>
                    <h3 class="t-op-nextlvl">@item.election_sym_name</h3>
                    <h3 class="t-op-nextlvl"><span class="font-view">@Html.Raw(item.election_sym_font_name)</span></h3>
                    <h3 class="t-op-nextlvl label-tag">@(item.election_sym_active ? "Active" : "In Active")</h3>
                </div>
            }
        </div>
    </div>
</div>