EMS_Front_End/EMS_Web_App/Controllers/CanditureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMS_Common.Handler;
using EMS_Common.Variables;
using EMS_Web_App.Models;
using EMS_Web_App.StaticFunc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace EMS_Web_App.Controllers
{
    [Authorize("Permission")]
    public class CanditureController : Controller
    {
        private readonly ITransactionHandler _api;
        private readonly IAPIHandler<election_parties> _apiPDD;
        private readonly APISettings _apiSettings;
        private readonly string _token;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CanditureController(ILogger<HomeController> logger,
                                            IOptions<APISettings> apiSettings,
                                            ITransactionHandler api,
                                            IAPIHandler<election_parties> apiPDD,
                                            IHttpContextAccessor httpContextAccessor)
        {
            _apiSettings = apiSettings.Value;
            _api = api;
            _apiPDD = apiPDD;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext!.Session.GetString(Constant.__TOKEN__)!;
        }
        public async Task<IActionResult> Index()
        {
            APIResponse response = await _api.GetDataList(_token, _apiSettings.BaseURL, Constant.GetCanditure);
            List<election_contesting_candidate_list> result = GenericFunc.ExtractJsonData<List<election_contesting_candidate_list>>(response.Data!.ToString());
            return View(result);
        }
        public async Task<IActionResult> Add()
        {
            await LoadData();
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            await LoadData();
            APIResponse response = await _api.GetDataById(_token, _apiSettings.BaseURL, Constant.GetCanditureById, id.ToString());
            election_contesting_candidate result = GenericFunc.ExtractJsonData<election_contesting_candidate>(response.Data!.ToString());
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] election_contesting_candidate model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.AddData(_token, _apiSettings.BaseURL, Constant.AddCanditure, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        await LoadData();
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    await LoadData();
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] election_contesting_candidate model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    APIResponse result = await _api.UpdateData(_token, _apiSettings.BaseURL, Constant.UpdateCanditure, model);

                    if (result.IsSuccess)
                    {
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Success, result.Message);
                    }
                    else
                    {
                        await LoadData();
                        TempData["alertMsg"] = Constant.ShowAlert(Alerts.Danger, result.Message);
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    await LoadData();
                    ModelState.AddModelError("", "Invalid data.");
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
        public async Task<string> GetActiveCities(int id)
        {
            var result = await _api.GetActiveCity(_apiSettings.BaseURL, Constant.GetDDCity, id);
            return JsonConvert.SerializeObject(result);
        }
        private async Task<bool> LoadData()
        {
            var states = await _api.GetActiveList(_apiSettings.BaseURL, Constant.GetDDState);

            var parties = await _apiPDD.GetAllData(_token, _apiSettings.BaseURL, Constant.PartyGetAll);

            APIResponse elections = await _api.GetDataList(_token, _apiSettings.BaseURL, Constant.GetActiveElectionList);
            List<election_year_to_date> result = GenericFunc.ExtractJsonData<List<election_year_to_date>>(elections.Data!.ToString());

            APIResponse users = await _api.GetDataList(_token, _apiSettings.BaseURL, Constant.GetActiveUsers);
            List<election_user> Rusers = GenericFunc.ExtractJsonData<List<election_user>>(users.Data!.ToString());

            if (states != null || result != null || parties != null || Rusers != null)
            {
                if (states != null)
                    ViewBag.StateDrpList = new SelectList(states, "election_state_id", "election_state_name");

                if (result != null)
                    ViewBag.ElectionDrpList = new SelectList(result, "election_id", "election_name");

                if (parties != null)
                    ViewBag.PartyDrpList = new SelectList(parties, "election_party_id", "election_party_name");

                if (Rusers != null)
                    ViewBag.UserDrpList = new SelectList(Rusers, "election_user_id", "election_voter_name");

                return true;
            }
            else
                return false;
        }
    }
}

EMS_Front_End/EMS_Web_App/Views/Canditure/Add.cshtml
@model election_contesting_candidate
@{
    ViewData["Title"] = "Add Candidate";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Canditure" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Add" asp-controller="Canditure" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_id, ViewBag.ElectionDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_party_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_party_id, ViewBag.PartyDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_party_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_state_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_state_id, ViewBag.StateDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown", @onchange = "CallCity()" })
                    @Html.ValidationMessageFor(model => model.election_state_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    <input type="hidden" id="ddcity" value="@Model.election_city_id" />
                    @Html.LabelFor(model => model.election_city_id, htmlAttributes: new { @class = "control-label" })
                    <select class="dropdown" asp-for="election_city_id"></select>
                    @Html.ValidationMessageFor(model => model.election_city_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_user_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_user_id, ViewBag.UserDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_user_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        function CallCity() {
            $.ajax({
                type: "GET",
                url: "/Canditure/GetActiveCities/" + $("#election_state_id").val(),
                success: function (data) {
                    var result = JSON.parse(data);
                    var s = '<option value="">--Select--</option>';
                    if (result != null) {
                        for (var i = 0; i < result.length; i++) {
                            s += '<option value="' + result[i].election_city_id + '">' + result[i].election_city_name + '</option>';
                        }
                    }
                    $("#election_city_id").html(s);
                }
            });
        }
        function SetCity() {
            var dv = $("#ddcity").val();
            if (dv != "")
                $('#election_city_id').val(dv);
        }
        CallCity();
        setTimeout(function () { SetCity(); }, 500);  
    </script>
}

EMS_Front_End/EMS_Web_App/Views/Canditure/Edit.cshtml
@model election_contesting_candidate
@{
    ViewData["Title"] = "Edit Candidate";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Canditure" asp-action="Index"><input type="button" class="view" value="Back" /></a>
    </div>
    <div class="report-body">
        <form asp-action="Add" asp-controller="Canditure" method="post">
            <div class="report-topic-heading">
                <div asp-validation-summary="ModelOnly" class="text-danger t-op"></div>
            </div>
            <input type="hidden" asp-for="election_contest_id" />
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_id, ViewBag.ElectionDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_party_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_party_id, ViewBag.PartyDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_party_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_state_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_state_id, ViewBag.StateDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown", @onchange = "CallCity()" })
                    @Html.ValidationMessageFor(model => model.election_state_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-group">
                    <input type="hidden" id="ddcity" value="@Model.election_city_id" />
                    @Html.LabelFor(model => model.election_city_id, htmlAttributes: new { @class = "control-label" })
                    <select class="dropdown" asp-for="election_city_id"></select>
                    @Html.ValidationMessageFor(model => model.election_city_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(model => model.election_user_id, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.election_user_id, ViewBag.UserDrpList as SelectList, "--Select--", htmlAttributes: new { @class = "dropdown" })
                    @Html.ValidationMessageFor(model => model.election_user_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group text-right">
                    <button type="submit" class="view">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        function CallCity() {
            $.ajax({
                type: "GET",
                url: "/Canditure/GetActiveCities/" + $("#election_state_id").val(),
                success: function (data) {
                    var result = JSON.parse(data);
                    var s = '<option value="">--Select--</option>';
                    if (result != null) {
                        for (var i = 0; i < result.length; i++) {
                            s += '<option value="' + result[i].election_city_id + '">' + result[i].election_city_name + '</option>';
                        }
                    }
                    $("#election_city_id").html(s);
                }
            });
        }
        function SetCity() {
            var dv = $("#ddcity").val();
            if (dv != "")
                $('#election_city_id').val(dv);
        }
        CallCity();
        setTimeout(function () { SetCity(); }, 500);      
    </script>
}

EMS_Front_End/EMS_Web_App/Views/Canditure/Index.cshtml
@model List<election_contesting_candidate_list>
@{
    ViewData["Title"] = "List of Candidate";
}
<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">@ViewData["Title"]</h1>
        <a asp-controller="Canditure" asp-action="Add"><input type="button" class="view" value="Create" /></a>
    </div>
    <div class="report-body">
        <div class="report-topic-heading">
            <h3 class="t-op">+</h3>
            <h3 class="t-op">Election Name</h3>
            <h3 class="t-op">Party Name</h3>
            <h3 class="t-op">Candidate Name</h3>
            <h3 class="t-op">Election State</h3>
            <h3 class="t-op">Election City</h3>
        </div>
        <div class="items">
            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    <div class="item1">
                        <h3 class="t-op-nextlvl">
                            @if (item.election_canditure_edit)
                            {
                                <a asp-controller="Canditure" asp-action="Edit" asp-route-id="@item.election_contest_id"><i class="fa-solid fa-pen-to-square"></i></a>
                            }
                            else
                            {
                                <a><i class="fa-solid fa-square"></i></a>

                            }
                        </h3>
                        <h3 class="t-op-nextlvl">@item.election_name</h3>
                        <h3 class="t-op-nextlvl">@item.election_party_name</h3>
                        <h3 class="t-op-nextlvl">@item.election_voter_name</h3>
                        <h3 class="t-op-nextlvl">@item.election_state_name</h3>
                        <h3 class="t-op-nextlvl">@item.election_city_name</h3>
                    </div>
                }
            }
        </div>
    </div>
</div>